name: dajek
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  lottie: 1.4.3
  flutter_map: ^0.13.0
  latlong2: ^0.8.1
  flutter_polyline_points: 1.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Ubuntu
      fonts: 
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
    - family: IconHome
      fonts: 
        - asset: assets/icons/IconHome.ttf
  uses-material-design: true

